<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\GithubRepoModel.cs" />
    <Compile Remove="Models\ProjectViewModel.cs" />
    <Compile Remove="Models\RepoContentModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\StyleSheet.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
  </ItemGroup>

  <ItemGroup>
    <TypeScriptCompile Include="ClientApp\react-ui\src\components\HeroSection.ts" />
  </ItemGroup>

</Project>
